spring:
  application: toto
nearmi:
  config:
    dbName: 'nearmi-dev'
    dbUsername: 'nearmi-dev'
    dbPassword: 'dev@password'
    cluster: 'cluster0.kvkgz.mongodb.net'

keycloak:
  auth-server-url: http://auth.nearmi-dev/
  realm: nearmi-dev
  bearerOnly: true
  ssl-required: external
  resource: nearmi-dev
  cors: false
  confidential-port: 0